name: Build & Push to Docker Hub
on:
  push: { branches: [master] }
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/smartassist:latest .
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartassist:latest
